apiVersion: v1
kind: Service
metadata:
  name: command-service-nodeport-srv
spec:
  type: NodePort
  selector:
    app: commandservice
  ports:
    - name: commandservice
      protocol: TCP
      port: 8080
      targetPort: 8080
