apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: acme.com
      http:
        paths:
          - path: /api/platforms
            pathType: Prefix
            backend:
              service:
                name: platform-clusterip-service
                port:
                  number: 80
          - path: /api/cs/platforms
            pathType: Prefix
            backend:
              service:
                name: command-clusterip-service
                port:
                  number: 80
